local/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['web']], function() {
	
// Route::get('/', function(){return view('welcome');})->name('welcome');
	
	// Route::get('/home', 'HomeController@index');
	Route::get('/users/logout', 'Auth\LoginController@userLogout')->name('user.logout');

	Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
	Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');

// Authentication Routes
	Auth::routes();


// Admin (Backend)
	Route::prefix('admin')->group(function(){
		Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
		Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
		Route::get('/', 'AdminController@index')->name('admin.dashboard'); //Được gọi trong Middleware/RedirectIfAuthenticated.php/handle.
		// Search
		Route::get('/search', 'AdminController@getSearch');
		Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

	// Password Reset Routes
		Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');

		Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
		Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset')->name('admin.password.update');
		Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');

	// Categories
		Route::resource('categories', 'CategoryController', ['except' => ['create']]);

	// Sub Category
		Route::resource('sub-categories', 'SubCategoryController', ['except' => ['create']]);

	// Slider
		Route::resource('sliders', 'SliderController', ['except' => ['create']]);

	// Product
		Route::resource('products', 'ProductController');

	// Comment
		Route::get('comments', 'AdminController@getComment')->name('admin.comments');
	// Show Users
		Route::get('users', 'AdminController@getUsers')->name('admin.users');
	});

// Home page
	Route::get('/', 'PagesController@getHome')->name('home');
	
// About page
	Route::get('about.html', 'PagesController@getAbout')->name('about');

// Women, men, kids pages
	Route::get('pages/{id}.html', 'PagesController@getPages')->name('pages');

// Show Products
	Route::get('products/{id}.html', 'PagesController@getProducts')->name('products');

// Show Product Detail
	Route::get('product/{id}.html', 'PagesController@getProduct')->name('product');

// Comment
	Route::post('product/{id}.html', 'CommentController@postComment');

// Search
	Route::get('search', 'PagesController@getSearch');

// Cart
	Route::group(['prefix'=>'cart'], function() {
		Route::get('add/{id}','CartController@getAddCart');
		Route::get('show','CartController@getShowCart');
		Route::get('delete/{id}','CartController@getDeleteCart');
		Route::get('update','CartController@getUpdateCart');
		Route::post('show','CartController@postComplete');
		Route::get('complete','CartController@getComplete');

		// Print Invoice PDF
		Route::get('invoice', 'CartController@getInvoice')->name('invoice');
	});
	

});

local/resources/views/about.blade.php
@extends('layouts.master')

@section('head.title')
	| About
@stop

@section ('body.content')

<!--CONTENT-->
<section class="content-page">
    <!--SECTION-->
    <div class="section popular on-show">
		<div class="section-title">
			<h1>About</h1>
		</div>
		<div class="jumbotron container" style="text-align: left;">
			<h6>Welcome to Cheetah's house! Here, every word, every detail and image is evidence bearing Cheetah's history for 100 years, and is constantly growing. All proud achievements of Cheetah are inseparable by four classic product lines: Chuck Taylor All Star, Star Chevron, Jack Purcell and One Star. In all areas such as music, sports, art and fashion trends, each of these products has a certain influence, as if conveying a message of "Creative spirit." that Cheetah is pursuing is endless, is an unlimited transformation "</h6>

			<h6>Everyone has a history - like a story that records what they have experienced. Cheetah history is the same, but this is a series of very cool stories, which have led a brand to the present day and become the direction for the future of a brand. When it comes to a person or an event, we are all aware that the importance is not about the history, or how old it is but the achievements made are what people care about. . Here is a story about us - Cheetah brand - the story that people will feel interesting and love it</h6>
		</div>
<section class="about">
	<div class="information">
		<center><h1>Information's Cheetah Team</h1></center>
	</div>
	<h2 style="text-align:center">User Profile Card</h2>
	<br><br><hr>
	<div class="row">
		<div class="col-sm-4">
			<div class="card" style="border:solid">
				<img src="https://chibi.info/wp-content/uploads/2016/12/one-piece-13.jpg" alt="Minto" style="width:100%">
				<h1>Minh Nguy Dinh</h1>
				<p class="title">Founder</p>
				<p>Aptech</p>
				<div class="contact" style="margin: 24px 0;">
					<a href="#"><i class="fa fa-dribbble"></i></a> 
					<a href="#"><i class="fa fa-twitter"></i></a>  
					<a href="#"><i class="fa fa-linkedin"></i></a>  
					<a href="#"><i class="fa fa-facebook"></i></a> 
				</div>
				<p><button>Contact</button></p>
			</div>	
		</div>
		<div class="col-sm-4">
			<div class="card" style="border:solid">
				<img src="https://cdn.vox-cdn.com/thumbor/JBJzwCXmTJs0NgnFtSPm_f5SMyw=/0x0:2000x1000/1200x800/filters:focal(654x138:974x458)/cdn.vox-cdn.com/uploads/chorus_image/image/59408999/Thanos_MCU.0.jpg" alt="ChiDiep" style="width:100%">
				<h1>Diep Huynh</h1>
				<p class="title">Founder</p>
				<p>Aptech</p>
				<div class="contact" style="margin: 24px 0;">
					<a href="#"><i class="fa fa-dribbble"></i></a> 
					<a href="#"><i class="fa fa-twitter"></i></a>  
					<a href="#"><i class="fa fa-linkedin"></i></a>  
					<a href="#"><i class="fa fa-facebook"></i></a> 
				</div>
				<p><button>Contact</button></p>
			</div>	
		</div>
		<div class="col-sm-4">
			<div class="card" style="border:solid">
				<img src="https://www.ebony.com/wp-content/uploads/2017/03/spiderman.jpg" alt="ThanhLe" style="width:100%;height:150%" >
				<h1>Thanh Le </h1>
				<p class="title">Founder</p>
				<p>Aptech</p>
				<div class="contact" style="margin: 24px 0;">
					<a href="#"><i class="fa fa-dribbble"></i></a> 
					<a href="#"><i class="fa fa-twitter"></i></a>  
					<a href="#"><i class="fa fa-linkedin"></i></a>  
					<a href="#"><i class="fa fa-facebook"></i></a> 
				</div>
				<p><button>Contact</button></p>
			</div>	
		</div>
	</div>
	<br><br><br>
</section>
</div>
</section>
@endsection

local/resources/views/admin.blade.php
@extends('layouts.admin-master')

@section('head.title')
    Cheetah Admin
@stop

@section ('body.content')
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-3" style="border: 5px solid rgba(80,80,80,1); border-radius: 15px;">
           <div class="row">
                <div class="col-md-12">
                    <h4>CHEETAH's ADMIN</h4>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-12">
                    <ul>
                        <li style="padding-bottom: 5px;">
                            <a href="{{ route('categories.index')}}"><button class="btn btn-dark">Category</button></a>
                        </li>
                      
                        <li style="padding-bottom: 5px;">
                            <a href="{{ route('sub-categories.index')}}"><button class="btn btn-dark">Sub-Category</button></a>
                        </li>
                       
                        <li style="padding-bottom: 5px;">
                            <a href="{{ route('sliders.index')}}"><button class="btn btn-dark">Slider</button></a>
                        </li>
                     
                        <li style="padding-bottom: 5px;">
                            <a href="{{ route('products.index')}}"><button class="btn btn-dark">Product</button></a>
                        </li>
                      
                        <li style="padding-bottom: 5px;">
                            <a href="{{ route('admin.comments')}}"><button class="btn btn-dark">Comment</button></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    
        <div class="col-md-9">
            <center><h1>Customer's Information</h1></center>
            <br>
            <div class="table-responsive">
                <table class="table table-dark table-hover">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Gender</th>
                            <th>Address</th>
                            <th>Cellphone</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $user)
                        <tr>
                            <td>{{$user->id}}</td>
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                            <td>{{$user->gender}}</td>
                            <td>{{$user->address}}</td>
                            <td>{{$user->phone_number}}</td>                           
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

local/resources/views/adminSearch.blade.php
@extends('layouts.admin-master')

@section('head.title')
Cheetah Admin
@stop

@section ('body.content')
<div class="col-md-12">
	<div class="row">
		<div class="col-md-8">
			<h1>Result finding for <i>{{ $keyword }}</i></h1>
		</div>
		<div class="col-md-4"></div>
		
	</div>
	<br><hr>
	<div class="row">
		<h1>Product</h1>
		<br><br>
		<div class="table-responsive">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th style="padding: 5px 10px;">Id</th>
						<th style="padding: 5px 100px;">Name</th>
						<th style="padding: 5px 10px;">SubCategory</th>
						<th style="padding: 5px 30px;">Unit_Price</th>
						<th style="padding: 5px 20px;">Promotion_Price</th>
						<th style="padding: 5px 50px;">Image</th>
						<th style="padding: 5px 50px;">Color</th>
						<th style="padding: 5px 20px;">Size</th>
						<th style="padding: 5px 20px;">SKU</th>
						<th style="padding: 5px 20px;">Material</th>
						<th style="padding: 5px 20px;">Gender</th>
						<th style="padding: 5px 10px;">isNew</th>
						<th style="padding: 5px 10px;">isSale</th>
						<th style="padding: 5px 80px;"></th>
					</tr>
				</thead>
				<tbody>
					@foreach($items as $item)
					<tr>
						<td>{{ $item->id }}</td>
						<td>{{ $item->name }}</td>
						<td>{{ $item->id_sub_category }}</td>
						<td>{{ $item->unit_price }}</td>
						<td>{{ $item->promotion_price }}</td>
						<td>{{ $item->image }}</td>
						<td>{{ $item->color }}</td>
						<td>{{ $item->size }}</td>
						<td>{{ $item->SKU }}</td>
						<td>{{ $item->material }}</td>
						<td>{{ $item->gender }}</td>
						<td>{{ $item->isNew }}</td>
						<td>{{ $item->isSale }}</td>
						<td>
							{!! Html::linkRoute('products.show', 'View', array($item->id), array('class' => 'btn btn-success')) !!}
							{!! Html::linkRoute('products.edit', 'Edit', array($item->id), array('class' => 'btn btn-primary')) !!}
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>

		
	</div> <!-- end of .row-->
</div>
@endsection

local/resources/views/comment.blade.php
@extends('layouts.admin-master')

@section('head.title')
	Admin | Comments
@stop

@section ('body.content')
	<div class="row">
		<div class="col-md-12">
			<h1>Comments</h1>
			<br>
			<table class="table table-dark table-hover">
				<thead>
					<tr>
						<th>Id</th>
						<th>Name</th>
						<th>Email</th>
						<th>Content</th>
						<th>id_product</th>
						<th>Created at</th>
						<th>Updated at</th>
					</tr>
				</thead>
				<tbody>
					@foreach($comments as $comm)
						<tr>
							<td>{{$comm->id}}</td>
							<td>{{$comm->name}}</td>
							<td>{{$comm->email}}</td>
							<td>{{$comm->content}}</td>
							<td>{{$comm->id_product}}</td>
							<td>{{$comm->created_at}}</td>
							<td>{{$comm->updated_at}}</td>
						</tr>
					@endforeach
				</tbody>
			</table>

		</div>
		<!-- end of .col-md-12-->
	</div> <!-- end of .row-->
	{!! Html::linkRoute('admin.dashboard', '<< Back to Admin dashboard', array(), array('class' => 'btn btn-warning btn-block')) !!}
@endsection

local/resources/views/home.blade.php
@extends('layouts.master')

@section('head.title')
    
@stop

@section ('body.content')

<!--CONTENT-->
<section class="content-page">
    <!--SECTION-->
    <div class="section popular on-show">
        <div class="section-title">
            <h1>New Arrival</h1>
        </div>
        <!--POPULAR NAV-->
        <div class="section-box popular-nav">
            <div class="popular-nav-wrap">
         
                <div class="popular-nav-item">
                    <h2>Men</h2>
                    <div class="popular-nav-pic">
                        <img src="{{ asset('img/men.png') }}" alt="Men">
                    </div>
                    <a id="nav-1" href=""></a>
                </div>

                <div class="popular-nav-item">
                    <h2>Women</h2>
                    <div class="popular-nav-pic">
                        <img src="{{ asset('img/women.png') }}" alt="Women">
                    </div>
                    <a id="nav-2" href=""></a>
                </div>

                <div class="popular-nav-item">
                    <h2>Kids</h2>
                    <div class="popular-nav-pic">
                        <img src="{{ asset('img/kids.png') }}" alt="Kids">
                    </div>
                    <a id="nav-3" href=""></a>
                </div>

                <span class="popular-arrow" style="left: 15%"></span>
            </div>
        </div>
        <!--/POPULAR LIST-->

        <!--POPULAR-CONTENT-LIST-->
        <div class="section-box popular-list on-show">
            <!--POPULAR-CONTENT-WRAP-->
            <div class="popular-content-wrap">
                <!--POPULAR-COL (slider 1)-->
                <div class="popular-col" id="col-1">
                    <!--1st row of 4 shoes box-->
                    <div class="popular-col-wrap row">
                        <!--1st shoes box-->
                        @foreach($products as $item)
                            @if(($item->id_sub_category>5) && ($item->id_sub_category < 11))
                                <div class="popular-box">
                                    @if($item->isNew==1)
                                        <div class="icon-new"></div>               
                                    @endif
                                    @if($item->isSale==1)
                                        <div class="icon-sale"></div>
                                    @endif
                                    @foreach($subcategories as $subcate)
                                        @if($item->id_sub_category==$subcate->id)
                                            <span class="note">{{$subcate->name}}</span>
                                        @endif
                                    @endforeach
                                    <div class="popular-box-pic">
                                        <img src="{{ asset('local/storage/images/' . $item->image) }}" alt="{{$item->name}}">
                                    </div>
                                    <div class="popular-box-text">
                                        <h3>{{$item->name}}</h3>
                                        <h4># {{$item->SKU}}</h4>
                                        <div class="price">
                                            <span>{{ number_format($item->unit_price,0,'.',',') }} VND</span> 
                                        </div>
                                    </div>     
                                    <a class="go-detail" href="{{route('product',['id'=>$item->id])}}"></a>  
                            
                                </div> 
                            @endif
                        @endforeach
                    </div>
                </div>
                <!--/POPULAR-COL (slider 1)-->

                <!--POPULAR-COL (slider 2)-->
                <div class="popular-col" id="col-2">
                    <!--1st row of 4 shoes box-->
                    <div class="popular-col-wrap row">
                        <!--1st shoes box-->
                        @foreach($products as $item)
                            @if($item->id_sub_category < 6)
                                <div class="popular-box">
                                    @if($item->isNew==1)
                                        <div class="icon-new"></div>               
                                    @endif
                                    @if($item->isSale==1)
                                        <div class="icon-sale"></div>
                                    @endif
                                    @foreach($subcategories as $subcate)
                                        @if($item->id_sub_category==$subcate->id)
                                            <span class="note">{{$subcate->name}}</span>
                                        @endif
                                    @endforeach
                                    <div class="popular-box-pic">
                                        <img src="{{ asset('local/storage/images/' . $item->image) }}" alt="{{$item->name}}">
                                    </div>
                                    <div class="popular-box-text">
                                        <h3>{{$item->name}}</h3>
                                        <h4># {{$item->SKU}}</h4>
                                        <div class="price">
                                            <span>{{ number_format($item->unit_price,0,'.',',') }} VND</span> 
                                        </div>
                                    </div>
                                    <a class="go-detail" href="{{route('product',['id'=>$item->id])}}"></a>   
                                </div>
                            @endif
                        @endforeach
                    </div>
                </div>
                <!--/POPULAR-COL (slider 2)-->

                <!--POPULAR-COL (slider 3)-->
                <div class="popular-col" id="col-3">
                    <!--1st row of 4 shoes box-->
                    <div class="popular-col-wrap row">
                        <!--1st shoes box-->
                        @foreach($products as $item)
                            @if($item->id_sub_category>10)
                                <div class="popular-box">
                                    @if($item->isNew==1)
                                        <div class="icon-new"></div>               
                                    @endif
                                    @if($item->isSale==1)
                                        <div class="icon-sale"></div>
                                    @endif
                                    @foreach($subcategories as $subcate)
                                        @if($item->id_sub_category==$subcate->id)
                                            <span class="note">{{$subcate->name}}</span>
                                        @endif
                                    @endforeach
                                    <div class="popular-box-pic">
                                        <img src="{{ asset('local/storage/images/' . $item->image) }}" alt="{{$item->name}}">
                                    </div>
                                    <div class="popular-box-text">
                                        <h3>{{$item->name}}</h3>
                                        <h4># {{$item->SKU}}</h4>
                                        <div class="price">
                                            <span>{{ number_format($item->unit_price,0,'.',',') }} VND</span> 
                                        </div>
                                    </div>
                                    <a class="go-detail" href="{{route('product',['id'=>$item->id])}}"></a>   
                                    
                                </div>
                            @endif
                        @endforeach
                    </div>
                </div>
                <!--/POPULAR-COL (slider 3)-->
            </div>
            <!--/POPULAR-CONTENT-WRAP-->
        </div>
        <!--/POPULAR-CONTENT-LIST-->
    </div>
    <!--/SECTION-->
    <!--SHORTCUT-->
    <div class="section shortcut on-show" id="shortcut"> <!--2 circles box above footer-->
        <div class="section-box">
            <div class="shortcut-box on-show">
                <div class="shortcut-pic">
                    <img src="{{asset('img/apparel-300517.jpg')}}" alt="Classic">
                </div>
                @foreach($subcategories as $subcatalog) 
                    @if($subcatalog->id_category==1)                
                        <a href="{{route('products',['id'=>$subcatalog->id]=2)}}"></a>
                    @endif
                @endforeach 
            </div>
            <div class="shortcut-box on-show">
                <div class="shortcut-pic">
                    <img src="{{asset('img/access-300517.jpg')}}" alt="Bags">
                </div>
                @foreach($subcategories as $subcatalog) 
                    @if($subcatalog->id_category==1)                
                        <a href="{{route('products',['id'=>$subcatalog->id]=3)}}"></a>
                    @endif
                @endforeach          
            </div>
        </div>
    </div>
    <!--/SHORTCUT-->
</section>
<!--/CONTENT-->

@endsection

local/resources/views/pages.blade.php
@extends('layouts.master')

@section('head.title')
    | {{$cate->name}}
@stop

@section ('body.content')

<!--CONTENT-->
<section class="content-page">
    <!--SECTION-->
    <div class="section popular on-show">
        <div class="section-title">
            <h1>{{$cate->name}}</h1>
        </div>

        <!--POPULAR-CONTENT-LIST-->
        <div class="section-box popular-list on-show" >
            <!--POPULAR-CONTENT-WRAP-->
            <div class="popular-content-wrap">
                <div class="popular-col">
                    <!--1st row of 4 shoes box-->
                    <div class="popular-col-wrap row">
                        <!--1st shoes box-->
                        @foreach($items as $product)
                                <div class="popular-box">
                                    @if($product->isNew==1)
                                        <div class="icon-new"></div>               
                                    @endif
                                    @if($product->isSale==1)
                                        <div class="icon-sale"></div>
                                    @endif
                                    @foreach($subcategories as $subcate)
                                        @if($product->id_sub_category==$subcate->id)
                                            <span class="note">{{$subcate->name}}</span>
                                        @endif
                                    @endforeach
                                    <div class="popular-box-pic">
                                        <img src="{{ asset('local/storage/images/' . $product->image) }}" alt="{{$product->name}}">
                                    </div>
                                    <div class="popular-box-text">
                                        <h3>{{$product->name}}</h3>
                                        <h4># {{$product->SKU}}</h4>
                                        <div class="price">
                                            @if($product->promotion_price==0)
                                                <span><b>{{ number_format($product->unit_price,0,'.',',') }} VND</b></span> 
                                            @else 
                                                VND                                               
                                                <del class="cost-price">{{ number_format($product->unit_price,0,'.',',') }}</del> <span class="sale-price">{{ number_format($product->promotion_price,0,'.',',') }}</span>
                                            @endif 
                                        </div>
                                    </div>
                                    <a href="{{route('product',['id'=>$product->id])}}"></a>
                                </div>
                        @endforeach
                    </div>
                </div>

            </div>
            <!--/POPULAR-CONTENT-WRAP-->
        </div>
        <!--/POPULAR-CONTENT-LIST-->
    </div>
    <!--/SECTION-->
</section>
<!--/CONTENT-->

@endsection

local/resources/views/search.blade.php
@extends('layouts.master')

@section('head.title')
    | Search
@stop

@section ('body.content')
    <!--CONTENT-->
    <section class="content-page">
        <!--SECTION-->
        <div class="section popular on-show">
            <div class="section-title">
                <h1>Result finding for {{ $keyword }}</h1>
                 
            </div>
            <!--POPULAR-CONTENT-LIST-->
            <div class="section-box popular-list"  >
                <!--POPULAR-CONTENT-WRAP-->
                <div class="popular-content-wrap">
                    <!--POPULAR-COL (slider 1)-->
                    <div class="popular-col">
                        <!--1st row of 4 shoes box-->
                        <div class="popular-col-wrap row">
                            <!--1st shoes box-->
                            @foreach($items as $item)
                            <div class="popular-box">
                                     @foreach($subcategories as $subcate)
                                        @if($item->id_sub_category==$subcate->id)
                                            <span class="note">{{$subcate->name}}</span>
                                        @endif
                                    @endforeach
                                    <div class="popular-box-pic">
                                        <img src="{{ asset('local/storage/images/' . $item->image) }}" alt="{{$item->name}}">
                                    </div>
                                    <div class="popular-box-text">
                                        <h3>{{$item->name}}</h3>
                                        <h4># {{$item->SKU}}</h4>
                                        <div class="price">
                                            @if($item->promotion_price==0)
                                                <span><b>{{ number_format($item->unit_price,0,'.',',') }} VND</b></span> 
                                            @else 
                                                VND                                               
                                                <del class="cost-price">{{ number_format($item->unit_price,0,'.',',') }}</del> <span class="sale-price">{{ number_format($item->promotion_price,0,'.',',') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                    <a class="go-detail" href="{{route('product',['id'=>$item->id])}}"></a>  
                                </div>
                            @endforeach
                        </div>
                    </div>
                    <!--/POPULAR-COL (slider 1)-->
                </div>
                <!--/POPULAR-CONTENT-WRAP-->
            </div>
            <!--/POPULAR-CONTENT-LIST-->
        </div>
        <!--/SECTION-->
    </section>
    <!--/CONTENT-->
@endsection

    